// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbmjelrbdyoowcbtupwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibWplbHJiZHlvb3djYnR1cHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzEyNDMsImV4cCI6MjA3NDAwNzI0M30.AZ3ent6R57UCqJOwMBC4I7GZ901tDB8EEjlIN-qP39g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});